# Generated by Django 4.2.6 on 2023-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_credits_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credits',
            name='issuance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
