# Generated by Django 4.2.6 on 2023-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_credits_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='issuance_date',
            field=models.DateField(),
        ),
    ]
