# Generated by Django 4.2.6 on 2023-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_credits_issuance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='credits',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plans',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
