# Generated by Django 4.2.6 on 2023-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_credits_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(),
        ),
    ]
