# Generated by Django 4.2.6 on 2023-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_credits_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(null=True),
        ),
    ]
